USE mini_bank_cc;
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (1, 'Bruce Gallagher', '9954', 'Dorval');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (2, 'Nash Rutledge', '985260', 'Tarvisio');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (3, 'Stephen H. Gillespie', '6998DV', 'Naarden');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (4, 'Scarlet V. Morton', '79842', 'Zaragoza');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (5, 'Burke Montgomery', '7362', 'Sossano');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (6, 'Octavius W. Alexander', '9721', 'Toernich');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (7, 'Madison Roberson', '3325NL', 'Wollongong');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (8, 'Carolyn G. Buchanan', '60802', 'Gandhidham');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (9, 'Orson Justice', '00650', 'Bokaro Steel City');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (10, 'Mariam Wolfe', '77911', 'Helensburgh');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (11, 'Reed W. Haynes', 'BL2 6XX', 'Bensheim');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (12, 'Shannon Brewer', '20100', 'Pietrasanta');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (13, 'Drew Stevens', '642919', 'Colombo');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (14, 'Upton Schroeder', '08568', 'Newton Abbot');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (15, 'Sebastian H. Hull', '9998', 'Cannes');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (16, 'Carlos Brewer', '12035-536', 'Khanpur');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (17, 'Rylee S. Cain', '6409HG', 'Legal');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (18, 'Meghan Hopper', 'W1B 5ZX', 'Hudson Bay');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (19, 'Ciaran Herrera', '633750', 'Jambes');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (20, 'Amos X. Sims', '31128', 'Kırıkhan');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (21, 'Carly R. Henderson', '64-696', 'Ergani');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (22, 'Garrison Maldonado', '772344', 'Tuscaloosa');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (23, 'Leroy B. Carrillo', '7308', 'Villata');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (24, 'Jeanette Watson', '395894', 'Iquique');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (25, 'Cherokee Myers', '535357', 'Lieferinge');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (26, 'Savannah Z. Kline', '8945', 'Oudergem');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (27, 'Lunea S. Black', '921379', 'Ludvika');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (28, 'Jillian Austin', '21611', 'Logroño');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (29, 'Cairo Jarvis', '77069', 'Spiere-Helkijn');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (30, 'Amy B. Carrillo', '7145', 'Sandy');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (31, 'Glenna Black', '71257', 'Malloa');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (32, 'Edward Richmond', '98487', 'Montgomery');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (33, 'Jolene Goodman', '78338', 'Valera Fratta');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (34, 'Harding Whitehead', '2606', 'Elmshorn');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (35, 'Lana T. Pitts', '95152', 'Nampa');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (36, 'Colt I. Fitzgerald', '61813', 'Badalona');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (37, 'Raymond A. Chase', '154408', 'Lint');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (38, 'Eve D. Shaw', '10016', 'Overland Park');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (39, 'Caldwell Z. Graves', '263836', 'Kortessem');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (40, 'Gretchen A. Oneill', '52989', 'Greater Hobart');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (41, 'Porter Alston', '32921', 'Belmonte del Sannio');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (42, 'Daphne Buckley', '47-143', 'Veere');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (43, 'May W. Pace', '74565', 'Vancouver');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (44, 'Paloma U. Hale', '43472', 'Monte Giberto');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (45, 'Matthew Frederick', 'P4C 4E5', 'Korbach');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (46, 'Orli L. Gould', '42624-206', 'Pinneberg');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (47, 'Autumn Cunningham', '528000', 'Aurora');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (48, 'Vernon R. Rosales', '04095', 'Dornbirn');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (49, 'Hoyt Lowery', '6119', 'Mellery');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (50, 'Merrill Gaines', '16596', 'Sint-Jans-Molenbeek');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (51, 'Chantale Dominguez', '5844', 'Spiere-Helkijn');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (52, 'Frances T. Mcdonald', '51605', 'Erode');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (53, 'Clementine I. Oneill', 'G6X 5G7', 'Putignano');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (54, 'Ivory K. Patton', '01401', 'Aserrí');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (55, 'Bryar Guthrie', '2923WU', 'Elingen');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (56, 'Ralph Huffman', '2900RI', 'Maintal');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (57, 'Margaret L. Gates', '49391', 'Marystown');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (58, 'Jenna Mcdaniel', 'SR8 8KB', 'Wisbech');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (59, 'Kelly A. Zamora', '6785DZ', 'Voitsberg');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (60, 'Wilma M. Hardy', '126500', 'Hualpén');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (61, 'Ivor M. Kinney', '811271', 'Thurso');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (62, 'Hiram Chandler', '10-194', 'Stockerau');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (63, 'Sydnee Ewing', '45551', 'Baie-Comeau');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (64, 'Patience I. Ferguson', '5853LN', 'Shreveport');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (65, 'Ferdinand O. Duncan', '51315', 'Profondeville');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (66, 'Melodie Wilkinson', '652751', 'Gorzów Wielkopolski');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (67, 'Calista Stephens', '92984-806', 'Bedollo');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (68, 'Dai Jimenez', '23399', 'Bo‘lhe');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (69, 'Bell Wise', '23028', 'Pontey');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (70, 'Adrienne Holmes', '968310', 'Leighton Buzzard');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (71, 'Anthony Deleon', '543580', 'Carbonear');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (72, 'Benedict K. Mullen', '14295-002', 'Sant''Omero');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (73, 'Whitney G. England', '5063WX', 'Paignton');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (74, 'Beck E. Walters', '3725', 'Drumheller');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (75, 'Barry Jacobson', '5202VQ', 'Filey');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (76, 'Darryl Y. Houston', '057550', 'Boise');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (77, 'Mechelle Bonner', '11583', 'Beauvais');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (78, 'Julian Campbell', '10319', 'Athus');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (79, 'Ria L. Solis', '68311', 'Montone');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (80, 'Barrett Rowland', '6278', 'Fossato Serralta');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (81, 'Kuame Bradley', '52-577', 'Helmsdale');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (82, 'Clinton I. Vazquez', '8527', 'Hines Creek');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (83, 'Tashya G. Townsend', '975469', 'Fort McPherson');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (84, 'Germane R. Heath', '426645', 'Cargovil');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (85, 'Carla F. Barnett', 'HZ9W 6XG', 'Massello');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (86, 'Barbara P. Gibson', '628752', 'Kapuskasing');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (87, 'Zachery D. Mccall', '14146', 'Muiden');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (88, 'Emily K. Matthews', '51117', 'Newark');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (89, 'Len Russell', '8184', 'Broxburn');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (90, 'Anthony Bridges', '8139TV', 'A Coruña');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (91, 'Hasad Head', '304083', 'Heusden');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (92, 'Aquila Cameron', '18295', 'Prince Albert');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (93, 'Boris P. Craig', '529366', 'Sant''Agata Bolognese');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (94, 'Lani Hammond', '95601', 'Wolfsberg');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (95, 'Dale I. Stout', '50308', 'Lombardsijde');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (96, 'Cody Q. Guthrie', '622427', 'Humbeek');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (97, 'Hope U. Bush', '77708', 'San Giovanni in Galdo');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (98, 'Sybil Norman', '818104', 'Orbais');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (99, 'Clark Spencer', '84-443', 'Salice Salentino');
INSERT INTO customers (CustomerID, Name, ZipCode, City) VALUES (100, 'Cathleen Ramirez', '71514', 'Bahawalpur');